<link rel="stylesheet" href="/index.php/webhooks/static/get/t/css/f/bootstrap.css">

<div class="gm-bootstrap">
  <div class="container-fluid">
  
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">

        <div class="panel panel-default">

          <div class="panel-heading"><h3 class="panel-title">Allow [APP] run on this site?</h3></div>
          <div class="panel-body">

            <form class="form-inline" action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/webhooks/addApp"); ?>">

              <button type="submit" class="btn btn-primary">Allow</button>
              <a class="btn btn-danger" href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/webhooks"); ?>">Cancel</a>

            </form>

          </div>

        </div>

      </div>
    </div>
  
  </div>
</div>

