<link rel="stylesheet" href="/index.php/webhooks/static/get/t/css/f/bootstrap.css">

<div class="gm-bootstrap">
  <div class="container-fluid">
  
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">

        <div class="panel panel-default">

          <div class="panel-heading"><h3 class="panel-title">Allow <?php echo $this->app["domain"] ?> run on this site?</h3></div>
          <div class="panel-body">

            <form class="form-inline">

              <p>This application uses this events</p>
              <ul>
              <?php
              $events = $this->app->getEventsObject();
              foreach ( $events as $hook=>$url ) { 
              ?>
                <li><?php echo $hook; ?></li>
              <?php 
              } 
              ?>
              </ul>
              <p>and embeds these script to your site</p>
              <ul>
              <?php 
              $scripts = $this->app->getScriptsArray();
              foreach ( $scripts as $key=>$script ) { 
              ?>
                <li><?php echo $script ?></li>
              <?php 
              } 
              ?>
              </ul>

              <a class="btn btn-primary" href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/webhooks/grantAppInstall"); ?>">YES</a>
              <a class="btn btn-danger" href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/webhooks/deniedAppInstall"); ?>">NO</a>

            </form>

          </div>

        </div>

      </div>
    </div>
  
  </div>
</div>

