<link rel="stylesheet" href="/index.php/webhooks/static/get/t/css/f/bootstrap.css">

<div class="gm-bootstrap">
  <div class="container-fluid">
  
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">

        <div class="panel panel-default">

          <div class="panel-heading"><h3 class="panel-title">Allow [URL] run on this site?</h3></div>
          <div class="panel-body">

            <form class="form-inline">

              <button class="btn btn-primary">Allow</button>
              <button class="btn btn-danger">Cancel</button>

            </form>

          </div>

        </div>

      </div>
    </div>
  
  </div>
</div>

