<link rel="stylesheet" href="/index.php/webhooks/static/get/t/css/f/bootstrap.css">

<div class="gm-bootstrap">
  <div class="container-fluid">
  
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">

      <?php 
        $error = $this->getRequest()->getParams()["error"];
        if ($error){
      ?>

        <div class="alert alert-danger" role="alert"><?php echo $error;?></div>

      <?php } ?>


        <div class="panel panel-default">

          <div class="panel-heading"><h3 class="panel-title">Applications</h3></div>
          <div class="panel-body">

            <form class="form-inline" action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/webhooks/redirectToApp"); ?>">

              <div class="form-group">
                <label class="sr-only" for="app">App Url</label>
                <input type="url" class="form-control" id="app" name="app" placeholder="App Url" required>
              </div>

              <button type="submit" class="btn btn-primary">Add</button>

            </form>

          </div>

        </div>

      </div>
    </div>
  
  </div>
</div>

